# Generated by Django 2.0.7 on 2018-08-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bio',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
